# Generated by Django 2.2.7 on 2019-11-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobDetails',
            new_name='JobDetail',
        ),
    ]
