# Generated by Django 2.2.7 on 2019-11-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20191121_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='url',
            field=models.CharField(default='https://answer-4u.com/', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='job_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobdetails', to='portfolio.JobDetail'),
        ),
    ]
